name: Rust

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Rust
        uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Use cache
        uses: Swatinem/rust-cache@v2
      - name: Run code format
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
      - name: Run Check
        run: cargo check --all
      - name: Run Test
        run: cargo test --all-features
      - name: Run docs
        run: cargo doc --all-features --no-deps
